# Generated by Django 6.0.2 on 2026-02-17 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('publisher_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['last_name', 'first_name', 'publisher_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='RecipeDB_au_last_na_8983eb_idx'), models.Index(fields=['publisher_name'], name='RecipeDB_au_publish_42d55f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions')),
                ('source_file', models.CharField(blank=True, help_text='Original file path for OCR', max_length=500)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='OCR confidence score (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='recipes', to='RecipeDB.author')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(related_name='recipes', to='RecipeDB.genre')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text='Amount and unit (e.g., "2 cups", "500g", "1 tablespoon")', max_length=100)),
                ('notes', models.CharField(blank=True, help_text='e.g., "chopped", "diced"', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in recipe')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeDB.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeDB.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'ordering': ['order', 'ingredient__name'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='RecipeDB.RecipeIngredient', to='RecipeDB.ingredient'),
        ),
        migrations.CreateModel(
            name='RecipeURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('description', models.CharField(blank=True, help_text='Description of the URL', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/official source URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, help_text='URL has been verified to work')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='RecipeDB.recipe')),
            ],
            options={
                'verbose_name': 'Recipe URL',
                'verbose_name_plural': 'Recipe URLs',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source', models.CharField(help_text='Source of the rating', max_length=100)),
                ('review_text', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_ratings', to='RecipeDB.recipe')),
            ],
            options={
                'verbose_name': 'Published Rating',
                'verbose_name_plural': 'Published Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipe', 'score'], name='RecipeDB_pu_recipe__39f847_idx'), models.Index(fields=['-created_at'], name='RecipeDB_pu_created_1ae3f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Your rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, help_text='Your personal notes about this recipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_ratings', to='RecipeDB.recipe')),
            ],
            options={
                'verbose_name': 'Personal Rating',
                'verbose_name_plural': 'Personal Ratings',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['recipe', 'user'], name='RecipeDB_pe_recipe__484593_idx'), models.Index(fields=['user', '-updated_at'], name='RecipeDB_pe_user_id_491a86_idx'), models.Index(fields=['recipe', 'score'], name='RecipeDB_pe_recipe__e77703_idx')],
                'unique_together': {('recipe', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['recipe', 'order'], name='RecipeDB_re_recipe__39cfd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='RecipeDB_re_title_3c6239_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created_at'], name='RecipeDB_re_created_b9aa00_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['ocr_confidence'], name='RecipeDB_re_ocr_con_fcf805_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeurl',
            index=models.Index(fields=['recipe', '-is_primary'], name='RecipeDB_re_recipe__8c2c09_idx'),
        ),
    ]
