# Generated by Django 6.0.2 on 2026-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeDB', '0002_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='RecipeDB.author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='RecipeDB.genre'),
        ),
    ]
